// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blockMsg.proto

package luckyblock

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BlockMessage struct {
	ID                   string     `protobuf:"bytes,100,opt,name=ID,proto3" json:"ID,omitempty"`
	Version              string     `protobuf:"bytes,105,opt,name=version,proto3" json:"version,omitempty"`
	ParentID             string     `protobuf:"bytes,110,opt,name=parentID,proto3" json:"parentID,omitempty"`
	BlockNumber          uint64     `protobuf:"varint,115,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	Timestamp            int64      `protobuf:"varint,120,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Score                uint32     `protobuf:"varint,125,opt,name=score,proto3" json:"score,omitempty"`
	PeerID               string     `protobuf:"bytes,130,opt,name=peerID,proto3" json:"peerID,omitempty"`
	Transactions         []*any.Any `protobuf:"bytes,135,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BlockMessage) Reset()         { *m = BlockMessage{} }
func (m *BlockMessage) String() string { return proto.CompactTextString(m) }
func (*BlockMessage) ProtoMessage()    {}
func (*BlockMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockMsg_9558ddbdd1374cca, []int{0}
}
func (m *BlockMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockMessage.Unmarshal(m, b)
}
func (m *BlockMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockMessage.Marshal(b, m, deterministic)
}
func (dst *BlockMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockMessage.Merge(dst, src)
}
func (m *BlockMessage) XXX_Size() int {
	return xxx_messageInfo_BlockMessage.Size(m)
}
func (m *BlockMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BlockMessage proto.InternalMessageInfo

func (m *BlockMessage) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *BlockMessage) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *BlockMessage) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

func (m *BlockMessage) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *BlockMessage) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BlockMessage) GetScore() uint32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *BlockMessage) GetPeerID() string {
	if m != nil {
		return m.PeerID
	}
	return ""
}

func (m *BlockMessage) GetTransactions() []*any.Any {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockMessage)(nil), "luckyblock.BlockMessage")
}

func init() { proto.RegisterFile("blockMsg.proto", fileDescriptor_blockMsg_9558ddbdd1374cca) }

var fileDescriptor_blockMsg_9558ddbdd1374cca = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0xe5, 0x16, 0x0a, 0xbd, 0x96, 0x0e, 0x56, 0x25, 0x8e, 0x8a, 0xc1, 0x62, 0xf2, 0x94,
	0x4a, 0x30, 0x31, 0x82, 0xb2, 0x64, 0x80, 0xc1, 0xdf, 0xc0, 0x09, 0x47, 0x14, 0xb5, 0xb1, 0x23,
	0x9f, 0x83, 0xc8, 0xc0, 0xc2, 0xc2, 0xb7, 0x46, 0x48, 0x0e, 0xe5, 0xcf, 0xf8, 0xfb, 0xbd, 0x3b,
	0x3d, 0x3d, 0x58, 0x95, 0x7b, 0x5f, 0xed, 0x1e, 0xb8, 0xce, 0xba, 0xe0, 0xa3, 0x97, 0xb0, 0xef,
	0xab, 0xdd, 0x90, 0xe4, 0xe6, 0xa2, 0xf6, 0xbe, 0xde, 0xd3, 0x36, 0x25, 0x65, 0xff, 0xbc, 0xb5,
	0x6e, 0x18, 0xcf, 0xae, 0x3e, 0x05, 0x2c, 0xef, 0xd3, 0x27, 0x31, 0xdb, 0x9a, 0xe4, 0x0a, 0x26,
	0x45, 0x8e, 0x4f, 0x4a, 0xe8, 0xb9, 0x99, 0x14, 0xb9, 0x44, 0x38, 0x79, 0xa1, 0xc0, 0x8d, 0x77,
	0xd8, 0x24, 0x79, 0x40, 0xb9, 0x81, 0xd3, 0xce, 0x06, 0x72, 0xb1, 0xc8, 0xd1, 0xa5, 0xe8, 0x87,
	0xa5, 0x82, 0x45, 0xaa, 0x7e, 0xec, 0xdb, 0x92, 0x02, 0xb2, 0x12, 0xfa, 0xc8, 0xfc, 0x55, 0xf2,
	0x12, 0xe6, 0xb1, 0x69, 0x89, 0xa3, 0x6d, 0x3b, 0x7c, 0x55, 0x42, 0x4f, 0xcd, 0xaf, 0x90, 0x6b,
	0x38, 0xe6, 0xca, 0x07, 0xc2, 0x37, 0x25, 0xf4, 0x99, 0x19, 0x41, 0x9e, 0xc3, 0xac, 0x23, 0x0a,
	0x45, 0x8e, 0xef, 0x22, 0x15, 0x7e, 0xa3, 0xbc, 0x85, 0x65, 0x0c, 0xd6, 0xb1, 0xad, 0x62, 0xe3,
	0x1d, 0xe3, 0x87, 0x50, 0x53, 0xbd, 0xb8, 0x5e, 0x67, 0xe3, 0xf0, 0xec, 0x30, 0x3c, 0xbb, 0x73,
	0x83, 0xf9, 0x77, 0x5a, 0xce, 0x52, 0x76, 0xf3, 0x15, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x51, 0x39,
	0x1c, 0x40, 0x01, 0x00, 0x00,
}
